org: mcpp-community

teams:
  members:
    mode: auto
    team_slug: members

  vteam:
    mode: approval
    team_slug: vteam
    reviewers:
      users: ["sunrisepeak"]
      teams: ["coreteam"]  # 至少需要一个 coreteam 成员 + sunrisepeak